apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv2
spec:
  capacity:
    storage: 1Gi  # 원하는 크기로 설정
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc2
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-07902a8fefe0e088f  # 실제 EFS 파일 시스템 ID로 변경
    volumeAttributes:
      path: /mysql-data  # EFS에 데이터를 저장할 경로 지정
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi  # PV에서 정의한 크기와 일치해야 합니다
  storageClassName: efs-sc2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coupon-mysql
  labels:
    app: coupon-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coupon-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: coupon-mysql
    spec:
      containers:
        - name: coupon-mysql 
          image: mysql:8.0 
          args:
            - mysqld
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
            - --explicit_defaults_for_timestamp=1
          env:
            - name: MYSQL_DATABASE
              value: coupon 
            - name: MYSQL_PASSWORD
              value: "1234"
            - name: MYSQL_ROOT_PASSWORD
              value: "1234" 
            - name: MYSQL_USER
              value: abcd 
            - name: TZ 
              value: UTC 
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-data2
      restartPolicy: Always
      volumes:
        - name: mysql-data2
          persistentVolumeClaim:
            claimName: mysql-data2
---
apiVersion: v1
kind: Service
metadata:
  name: coupon-mysql
  labels:
     app: coupon-mysql
spec:
  selector:
    app: coupon-mysql
  ports:
   - name: mysql
     port: 3306
     targetPort: 3306
