apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: shop-back
  name: shop-back
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: shop-back  
  strategy:
  template:
    metadata:
      labels:
        io.kompose.service: shop-back
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          image: cloudbreak6th/shop-back:v1.0
          name: shop-back
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: shop-back
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing" # 외부 접근을 허용
    service.beta.kubernetes.io/aws-load-balancer-security-groups: "sg-02193707a5bb5776a" # 보안 그룹 ID 지정
  labels:
    io.kompose.service: shop-back
spec:
  type: LoadBalancer 
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    io.kompose.service: shop-back

